package rentalapp;

import controller.MobilController;
import controller.PelangganController;
import controller.PengembalianController;
import controller.PenyewaanController;
import controller.SopirController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Mobil;
import model.Pelanggan;
import model.Pengembalian;
import model.Penyewaan;
import model.Sopir;
import rentalapp.DialogPenyewaan.PenyewaanSelectListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ThinkPad
 */
public class PengembalianPanel extends javax.swing.JPanel {

    // Controllers
    private MobilController mobilController;
    private PelangganController pelangganController;
    private SopirController sopirController;
    private PenyewaanController penyewaanController;
    private PengembalianController pengembalianController;

    // Selected Penyewaan
    private Penyewaan selectedPenyewaan = null;

    /**
     * Creates new form PenyewaanPanel
     */
    public PengembalianPanel() {
        initComponents();
        // Initialize controllers
        mobilController = new MobilController();
        pelangganController = new PelangganController();
        sopirController = new SopirController();
        penyewaanController = new PenyewaanController();
        pengembalianController = new PengembalianController();

        // Set up the table
        setupTable();
        loadPengembalianData();

        // Set up button listeners
        setupButtonListeners();

        // Clear form initially
        clearForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelidmobil = new javax.swing.JLabel();
        labelnopolis = new javax.swing.JLabel();
        labelmerek = new javax.swing.JLabel();
        labeltahunmobil = new javax.swing.JLabel();
        labelhargasewa = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        labeldendamobil = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelidpelanggan = new javax.swing.JLabel();
        labelnamaplgn = new javax.swing.JLabel();
        labelnohp = new javax.swing.JLabel();
        labelalamat = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelidsopir = new javax.swing.JLabel();
        labelnamasopir = new javax.swing.JLabel();
        labelnosim = new javax.swing.JLabel();
        labeltarif = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        texttanggalkembali = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        labelketerlambatan = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labeltotalbayar = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnhitung = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        labeldenda = new javax.swing.JLabel();
        labelidpengembalian = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpengembalian = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        labelidpenyewaan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labeltanggalsewa = new javax.swing.JLabel();
        labelrencana = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        labelidpenyewaan3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labeltotalharga1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(28, 147, 239));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Pengembalian");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logo White.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mobil"));

        jLabel2.setText("ID Mobil");

        jLabel3.setText("No Polisi");

        jLabel4.setText("Merk");

        jLabel5.setText("Tahun");

        jLabel6.setText("Harga Sewa");

        labelidmobil.setText("-");

        labelnopolis.setText("-");

        labelmerek.setText("-");

        labeltahunmobil.setText("-");

        labelhargasewa.setText("-");

        jLabel23.setText("Denda/hari");

        labeldendamobil.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelidmobil, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labeldendamobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelnopolis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelmerek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labeltahunmobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelhargasewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelidmobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelnopolis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelmerek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltahunmobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelhargasewa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeldendamobil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pelanggan"));

        jLabel7.setText("ID Pelanggan");

        jLabel8.setText("Nama");

        jLabel9.setText("No Hp");

        jLabel10.setText("Alamat");

        labelidpelanggan.setText("-");

        labelnamaplgn.setText("-");

        labelnohp.setText("-");

        labelalamat.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelnohp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelidpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelnamaplgn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelidpelanggan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelnamaplgn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelnohp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelalamat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sopir"));

        jLabel11.setText("ID Sopir");

        jLabel12.setText("Nama");

        jLabel13.setText("No. SIM");

        jLabel15.setText("Tarif/Hari");

        labelidsopir.setText("-");

        labelnamasopir.setText("-");

        labelnosim.setText("-");

        labeltarif.setText("-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelidsopir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelnamasopir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelnosim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labeltarif, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelidsopir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelnamasopir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelnosim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltarif))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Pengembalian", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel5.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Tanggal Pengembalian");

        texttanggalkembali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Keterlambatan");

        labelketerlambatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelketerlambatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelketerlambatan.setText("-");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Total Bayar");

        labeltotalbayar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeltotalbayar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeltotalbayar.setText("-");

        btnsimpan.setText("Simpan");

        btnhitung.setText("Hitung");

        btnclear.setText("Bersihkan");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Denda");

        labeldenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeldenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeldenda.setText("-");

        labelidpengembalian.setText("-");

        jLabel25.setText("ID Pengembalian");

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelidpengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(texttanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelketerlambatan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labeldenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labeltotalbayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnhitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnclear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelidpengembalian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhapus))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(jLabel19))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labeldenda)
                                .addComponent(labeltotalbayar)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelketerlambatan, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addComponent(texttanggalkembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pengembalian", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tpengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tpengembalian);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Penyewaan"));

        jLabel18.setText("ID Peyewaan");

        labelidpenyewaan.setText("-");

        jLabel14.setText("Tanggal Sewa");

        labeltanggalsewa.setText("-");

        labelrencana.setText("-");

        jLabel20.setText("Rencana Pengembalian");

        jLabel21.setText("Total Hari");

        labelidpenyewaan3.setText("-");

        jLabel22.setText("Harga");

        labeltotalharga1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeltotalharga1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeltotalharga1.setText("-");

        jButton1.setText("List Penyewaan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(labeltanggalsewa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelrencana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelidpenyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(labelidpenyewaan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltotalharga1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator1)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelidpenyewaan3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelrencana))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelidpenyewaan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labeltanggalsewa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labeltotalharga1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnrefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnhapusActionPerformed
        int selectedRow = tpengembalian.getSelectedRow();
        if (selectedRow >= 0) {
            int idPengembalian = Integer.parseInt(tpengembalian.getValueAt(selectedRow, 0).toString());
            Pengembalian pengembalian = new Pengembalian();
            pengembalian.setIdPengembalian(idPengembalian);
            pengembalian.deletePengembalian();
            loadPengembalianData();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus", "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
        }
    }// GEN-LAST:event_btnhapusActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnrefreshActionPerformed
        loadPengembalianData();
    }// GEN-LAST:event_btnrefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelalamat;
    private javax.swing.JLabel labeldenda;
    private javax.swing.JLabel labeldendamobil;
    private javax.swing.JLabel labelhargasewa;
    private javax.swing.JLabel labelidmobil;
    private javax.swing.JLabel labelidpelanggan;
    private javax.swing.JLabel labelidpengembalian;
    private javax.swing.JLabel labelidpenyewaan;
    private javax.swing.JLabel labelidpenyewaan3;
    private javax.swing.JLabel labelidsopir;
    private javax.swing.JLabel labelketerlambatan;
    private javax.swing.JLabel labelmerek;
    private javax.swing.JLabel labelnamaplgn;
    private javax.swing.JLabel labelnamasopir;
    private javax.swing.JLabel labelnohp;
    private javax.swing.JLabel labelnopolis;
    private javax.swing.JLabel labelnosim;
    private javax.swing.JLabel labelrencana;
    private javax.swing.JLabel labeltahunmobil;
    private javax.swing.JLabel labeltanggalsewa;
    private javax.swing.JLabel labeltarif;
    private javax.swing.JLabel labeltotalbayar;
    private javax.swing.JLabel labeltotalharga1;
    private com.toedter.calendar.JDateChooser texttanggalkembali;
    private javax.swing.JTable tpengembalian;
    // End of variables declaration//GEN-END:variables

    /**
     * Set up the pengembalian data table
     */
    private void setupTable() {
        // Set up the table model
        String[] columns = {"ID", "ID Sewa", "Nama Pelanggan", "Merek Mobil", "Tanggal Kembali", "Keterlambatan",
            "Denda", "Total Bayar"};
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make cells non-editable
            }
        };
        tpengembalian.setModel(model);
    }

    /**
     * Load all pengembalian data to the table
     */
    private void loadPengembalianData() {
        DefaultTableModel model = (DefaultTableModel) tpengembalian.getModel();
        model.setRowCount(0); // Clear existing data

        List<Pengembalian> pengembalianList = new Pengembalian().getAllPengembalian();

        for (Pengembalian p : pengembalianList) {
            // Get penyewaan data to retrieve pelanggan and mobil info
            Penyewaan penyewaan = penyewaanController.getPenyewaanById(p.getIdSewa());
            String namaPelanggan = "-";
            String merekMobil = "-";

            if (penyewaan != null) {
                // Get pelanggan name
                Pelanggan pelanggan = pelangganController.getPelangganById(penyewaan.getIdPelanggan());
                if (pelanggan != null) {
                    namaPelanggan = pelanggan.getNama();
                }

                // Get mobil merek
                Mobil mobil = mobilController.getMobilById(penyewaan.getIdMobil());
                if (mobil != null) {
                    merekMobil = mobil.getMerk();
                }
            }

            model.addRow(new Object[]{
                p.getIdPengembalian(),
                p.getIdSewa(),
                namaPelanggan,
                merekMobil,
                p.getTglKembali(),
                p.getKeterlambatan() + " hari",
                "Rp " + p.getDenda(),
                "Rp " + p.getTotalBayar()
            });
        }
    }

    /**
     * Clear all form fields
     */
    private void clearForm() {
        // Clear labels
        labelidpenyewaan.setText("-");
        labeltanggalsewa.setText("-");
        labelrencana.setText("-");
        labelidpenyewaan3.setText("-"); // total hari
        labeltotalharga1.setText("-"); // harga

        // Clear mobil info
        labelidmobil.setText("-");
        labelnopolis.setText("-");
        labelmerek.setText("-");
        labeltahunmobil.setText("-");
        labelhargasewa.setText("-");
        labeldendamobil.setText("-");

        // Clear pelanggan info
        labelidpelanggan.setText("-");
        labelnamaplgn.setText("-");
        labelnohp.setText("-");
        labelalamat.setText("-");

        // Clear sopir info
        labelidsopir.setText("-");
        labelnamasopir.setText("-");
        labelnosim.setText("-");
        labeltarif.setText("-");

        // Clear calculation results
        labelketerlambatan.setText("-");
        labeldenda.setText("-");
        labeltotalbayar.setText("-");

        // Clear pengembalian info
        labelidpengembalian.setText("-");
        texttanggalkembali.setDate(null);

        selectedPenyewaan = null;
    }

    /**
     * Load penyewaan data to form
     */
    private void loadPenyewaanData(int idPenyewaan) {
        // Get penyewaan
        selectedPenyewaan = penyewaanController.getPenyewaanById(idPenyewaan);

        if (selectedPenyewaan == null) {
            JOptionPane.showMessageDialog(this, "Data penyewaan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if already returned
        if ("selesai".equals(selectedPenyewaan.getStatus())) {
            // JOptionPane.showMessageDialog(this, "Penyewaan ini sudah dikembalikan!",
            // "Information",
            // JOptionPane.INFORMATION_MESSAGE);
            // Load pengembalian data if exists
            Pengembalian pengembalian = pengembalianController.getPengembalianByIdSewa(idPenyewaan);
            if (pengembalian != null) {
                labelidpengembalian.setText(String.valueOf(pengembalian.getIdPengembalian()));
                texttanggalkembali.setDate(pengembalian.getTglKembali());
                labelketerlambatan.setText(String.valueOf(pengembalian.getKeterlambatan()) + " hari");
                labeldenda.setText("Rp " + pengembalian.getDenda());
                labeltotalbayar.setText("Rp " + pengembalian.getTotalBayar());
            }
        }

        // Set penyewaan info
        labelidpenyewaan.setText(String.valueOf(selectedPenyewaan.getIdSewa()));
        labeltanggalsewa.setText(selectedPenyewaan.getTglSewa().toString());
        labelrencana.setText(selectedPenyewaan.getTglKembaliRencana().toString());

        // Calculate lama sewa days between the dates
        long lamaSewa = (selectedPenyewaan.getTglKembaliRencana().getTime() - selectedPenyewaan.getTglSewa().getTime())
                / (1000 * 60 * 60 * 24);
        labelidpenyewaan3.setText(String.valueOf(lamaSewa) + " hari");

        labeltotalharga1.setText("Rp " + selectedPenyewaan.getTotalHarga());

        // Get and set mobil info
        Mobil mobil = mobilController.getMobilById(selectedPenyewaan.getIdMobil());
        if (mobil != null) {
            labelidmobil.setText(String.valueOf(mobil.getIdMobil()));
            labelnopolis.setText(mobil.getNoPolisi());
            labelmerek.setText(mobil.getMerk());
            labeltahunmobil.setText(String.valueOf(mobil.getTahun()));
            labelhargasewa.setText("Rp " + mobil.getHargaSewa());
            labeldendamobil.setText("Rp " + mobil.getDendaPerHari());
        }

        // Get and set pelanggan info
        Pelanggan pelanggan = pelangganController.getPelangganById(selectedPenyewaan.getIdPelanggan());
        if (pelanggan != null) {
            labelidpelanggan.setText(String.valueOf(pelanggan.getIdPelanggan()));
            labelnamaplgn.setText(pelanggan.getNama());
            labelnohp.setText(pelanggan.getNoTelepon());
            labelalamat.setText(pelanggan.getAlamat());
        }

        // Get and set sopir info
        if (selectedPenyewaan.getIdSopir() > 0) {
            Sopir sopir = sopirController.getSopirById(selectedPenyewaan.getIdSopir());
            if (sopir != null) {
                labelidsopir.setText(String.valueOf(sopir.getIdSopir()));
                labelnamasopir.setText(sopir.getNama());
                labelnosim.setText(sopir.getNoSim());
                labeltarif.setText("Rp " + sopir.getTarifPerHari());
            }
        } else {
            labelidsopir.setText("-");
            labelnamasopir.setText("-");
            labelnosim.setText("-");
            labeltarif.setText("-");
        }

    }

    /**
     * Calculate the fine and total payment
     */
    private void calculatePayment() {
        if (selectedPenyewaan == null) {
            JOptionPane.showMessageDialog(this, "Pilih data penyewaan terlebih dahulu!", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.util.Date returnDate = texttanggalkembali.getDate();

        if (returnDate == null) {
            JOptionPane.showMessageDialog(this, "Pilih tanggal pengembalian!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get the planned return date from the selected rental
        java.util.Date plannedReturnDate = selectedPenyewaan.getTglKembaliRencana();

        // Get denda per hari from mobil
        Mobil mobil = mobilController.getMobilById(selectedPenyewaan.getIdMobil());
        if (mobil == null) {
            JOptionPane.showMessageDialog(this, "Data mobil tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int dendaPerHari = mobil.getDendaPerHari();

        // Calculate days difference between planned and actual return dates
        // Remove time component for accurate day calculation
        java.util.Calendar cal1 = java.util.Calendar.getInstance();
        cal1.setTime(plannedReturnDate);
        cal1.set(java.util.Calendar.HOUR_OF_DAY, 0);
        cal1.set(java.util.Calendar.MINUTE, 0);
        cal1.set(java.util.Calendar.SECOND, 0);
        cal1.set(java.util.Calendar.MILLISECOND, 0);
        java.util.Calendar cal2 = java.util.Calendar.getInstance();
        cal2.setTime(returnDate);
        cal2.set(java.util.Calendar.HOUR_OF_DAY, 0);
        cal2.set(java.util.Calendar.MINUTE, 0);
        cal2.set(java.util.Calendar.SECOND, 0);
        cal2.set(java.util.Calendar.MILLISECOND, 0);
        long diffInMillis = cal2.getTimeInMillis() - cal1.getTimeInMillis();
        int diffInDays = (int) Math.ceil(diffInMillis / (1000.0 * 60 * 60 * 24));

        // Calculate keterlambatan and denda
        int keterlambatan = 0;
        int totalDenda = 0;

        if (diffInDays > 0) {
            keterlambatan = diffInDays;
            totalDenda = keterlambatan * dendaPerHari;
        }

        // Calculate total bayar (original rental cost + any late fees)
        int totalBayar = selectedPenyewaan.getTotalHarga() + totalDenda;

        // Update the UI
        labelketerlambatan.setText(keterlambatan + " hari");
        labeldenda.setText("Rp " + totalDenda);
        labeltotalbayar.setText("Rp " + totalBayar);
    }

    /**
     * Save the return data to database
     */
    private void savePengembalian() {
        if (selectedPenyewaan == null) {
            JOptionPane.showMessageDialog(this, "Pilih data penyewaan terlebih dahulu!", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Check if already calculated
        if (labelketerlambatan.getText().equals("-") || labeldenda.getText().equals("-")
                || labeltotalbayar.getText().equals("-")) {
            JOptionPane.showMessageDialog(this, "Hitung terlebih dahulu sebelum menyimpan!", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get values
        int idSewa = selectedPenyewaan.getIdSewa();

        java.util.Date returnDate = texttanggalkembali.getDate();

        if (returnDate == null) {
            JOptionPane.showMessageDialog(this, "Pilih tanggal pengembalian!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Convert to SQL Date after removing time component
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(returnDate);
        cal.set(java.util.Calendar.HOUR_OF_DAY, 0);
        cal.set(java.util.Calendar.MINUTE, 0);
        cal.set(java.util.Calendar.SECOND, 0);
        cal.set(java.util.Calendar.MILLISECOND, 0);
        Date sqlReturnDate = new Date(cal.getTimeInMillis());

        // Parse the keterlambatan and denda values from the UI
        int keterlambatan = 0;
        try {
            keterlambatan = Integer.parseInt(labelketerlambatan.getText().replace(" hari", ""));
        } catch (NumberFormatException e) {
            // Use the calculated value instead
        }

        // Catatan is optional - could be improved to allow user input
        String catatan = "Pengembalian pada " + sqlReturnDate
                + (keterlambatan > 0 ? ", terlambat " + keterlambatan + " hari" : "");

        // Process the return
        boolean success = pengembalianController.prosesPengembalian(idSewa, sqlReturnDate, catatan);

        if (success) {
            JOptionPane.showMessageDialog(this, "Pengembalian berhasil disimpan!", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            // Refresh table and clear form
            loadPengembalianData();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan pengembalian!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Set up button listeners
     */
    private void setupButtonListeners() {
        // Button to show list of penyewaan
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Create and show the dialog
                java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(PengembalianPanel.this);
                java.awt.Frame parent = window instanceof java.awt.Frame ? (java.awt.Frame) window : null;
                DialogPenyewaan dialog = new DialogPenyewaan(parent, true);

                // Set the listener to handle selection
                dialog.setPenyewaanSelectListener(new PenyewaanSelectListener() {
                    @Override
                    public void onPenyewaanSelected(int idPenyewaan) {
                        loadPenyewaanData(idPenyewaan);
                    }
                });

                // Show the dialog
                dialog.setLocationRelativeTo(parent);
                dialog.setVisible(true);
            }
        });

        // Button to calculate fine and payment
        btnhitung.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                calculatePayment();
            }
        });

        // Button to save return data
        btnsimpan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                savePengembalian();
            }
        });

        // Button to clear form
        btnclear.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                clearForm();
            }
        });

        // Add row selection listener to the table
        tpengembalian.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tpengembalian.getSelectedRow();
                if (selectedRow >= 0) {
                    // Get the ID Sewa from the selected row
                    int idSewa = (int) tpengembalian.getValueAt(selectedRow, 1);
                    loadPenyewaanData(idSewa);
                }
            }
        });
    }
}
