/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rentalapp;

/**
 * SidebarPanel handles navigation between different panels of the application
 * It contains navigation buttons that trigger panel switching in MainFrame
 *
 * @author ThinkPad
 */
public class SidebarPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
     * Creates new form SidebarPanel
     */
    public SidebarPanel() {
        initComponents();
    }

    /**
     * Sets the reference to the parent MainFrame for navigation
     *
     * @param mainFrame The parent MainFrame that contains this panel
     */
    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboard = new javax.swing.JLabel();
        btnPelanggan = new javax.swing.JLabel();
        btnMobil = new javax.swing.JLabel();
        btnSopir = new javax.swing.JLabel();
        btnKaryawan = new javax.swing.JLabel();
        btnPenyewaan = new javax.swing.JLabel();
        bntPenyewaan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(200, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDashboard.setText("Dashboard");
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setMaximumSize(new java.awt.Dimension(60, 16));
        btnDashboard.setMinimumSize(new java.awt.Dimension(60, 16));
        btnDashboard.setPreferredSize(new java.awt.Dimension(60, 16));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        btnPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnPelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPelanggan.setText("Data Pelanggan");
        btnPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPelangganMouseClicked(evt);
            }
        });
        add(btnPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 50));

        btnMobil.setForeground(new java.awt.Color(255, 255, 255));
        btnMobil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMobil.setText("Data Mobil");
        btnMobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMobilMouseClicked(evt);
            }
        });
        add(btnMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 50));

        btnSopir.setForeground(new java.awt.Color(255, 255, 255));
        btnSopir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSopir.setText("Data Sopir");
        btnSopir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSopir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSopirMouseClicked(evt);
            }
        });
        add(btnSopir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        btnKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btnKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnKaryawan.setText("Data Karyawan");
        btnKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKaryawanMouseClicked(evt);
            }
        });
        add(btnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 50));

        btnPenyewaan.setForeground(new java.awt.Color(255, 255, 255));
        btnPenyewaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPenyewaan.setText("Data Penyewaan");
        btnPenyewaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPenyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPenyewaanMouseClicked(evt);
            }
        });
        add(btnPenyewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 50));

        bntPenyewaan.setForeground(new java.awt.Color(255, 255, 255));
        bntPenyewaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntPenyewaan.setText("Data Pengembalian");
        bntPenyewaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntPenyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntPenyewaanMouseClicked(evt);
            }
        });
        add(bntPenyewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSopirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSopirMouseClicked
        navigateToPanel(MainFrame.PanelType.SOPIR, "Data Sopir");
    }//GEN-LAST:event_btnSopirMouseClicked

    private void btnKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaryawanMouseClicked
        navigateToPanel(MainFrame.PanelType.KARYAWAN, "Data Karyawan");
    }//GEN-LAST:event_btnKaryawanMouseClicked

    private void btnPenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenyewaanMouseClicked
        navigateToPanel(MainFrame.PanelType.PENYEWAAN, "Data Penyewaan");
    }//GEN-LAST:event_btnPenyewaanMouseClicked

    private void bntPenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntPenyewaanMouseClicked
        navigateToPanel(MainFrame.PanelType.PENGEMBALIAN, "Data Pengembalian");
    }//GEN-LAST:event_bntPenyewaanMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnDashboardMouseClicked
        navigateToPanel(MainFrame.PanelType.DASHBOARD, "Dashboard");
    }// GEN-LAST:event_btnDashboardMouseClicked

    private void btnPelangganMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnPelangganMouseClicked
        navigateToPanel(MainFrame.PanelType.PELANGGAN, "Data Pelanggan");
    }// GEN-LAST:event_btnPelangganMouseClicked

    private void btnMobilMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnMobilMouseClicked
        navigateToPanel(MainFrame.PanelType.MOBIL, "Data Mobil");
    }// GEN-LAST:event_btnMobilMouseClicked

    /**
     * Helper method to handle panel navigation and error logging
     *
     * @param panelType The type of panel to navigate to
     * @param panelName The display name of the panel (for logging)
     */
    private void navigateToPanel(MainFrame.PanelType panelType, String panelName) {
        System.out.println(panelName + " clicked");
        if (mainFrame != null) {
            mainFrame.showPanel(panelType);
        } else {
            System.err.println("MainFrame reference is null!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bntPenyewaan;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnKaryawan;
    private javax.swing.JLabel btnMobil;
    private javax.swing.JLabel btnPelanggan;
    private javax.swing.JLabel btnPenyewaan;
    private javax.swing.JLabel btnSopir;
    // End of variables declaration//GEN-END:variables
}
