/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rentalapp;

/**
 * SidebarPanel handles navigation between different panels of the application
 * It contains navigation buttons that trigger panel switching in MainFrame
 *
 * @author ThinkPad
 */
public class SidebarPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
     * Creates new form SidebarPanel
     */
    public SidebarPanel() {
        initComponents();
    }

    /**
     * Sets the reference to the parent MainFrame for navigation
     *
     * @param mainFrame The parent MainFrame that contains this panel
     */
    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboard = new javax.swing.JLabel();
        btnPelanggan = new javax.swing.JLabel();
        btnMobil = new javax.swing.JLabel();
        btnSopir = new javax.swing.JLabel();
        btnKaryawan = new javax.swing.JLabel();
        btnPenyewaan = new javax.swing.JLabel();
        bntPenyewaan = new javax.swing.JLabel();
        bntlogout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(200, 300));

        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dashboard.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setIconTextGap(10);
        btnDashboard.setMaximumSize(new java.awt.Dimension(60, 16));
        btnDashboard.setMinimumSize(new java.awt.Dimension(60, 16));
        btnDashboard.setPreferredSize(new java.awt.Dimension(60, 16));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });

        btnPelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Customer.png"))); // NOI18N
        btnPelanggan.setText("Data Pelanggan");
        btnPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPelanggan.setIconTextGap(10);
        btnPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPelangganMouseClicked(evt);
            }
        });

        btnMobil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Mobil.png"))); // NOI18N
        btnMobil.setText("Data Mobil");
        btnMobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMobil.setIconTextGap(10);
        btnMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMobilMouseClicked(evt);
            }
        });

        btnSopir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSopir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Supir.png"))); // NOI18N
        btnSopir.setText("Data Sopir");
        btnSopir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSopir.setIconTextGap(10);
        btnSopir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSopirMouseClicked(evt);
            }
        });

        btnKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Karyawan.png"))); // NOI18N
        btnKaryawan.setText("Data Karyawan");
        btnKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKaryawan.setIconTextGap(10);
        btnKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKaryawanMouseClicked(evt);
            }
        });

        btnPenyewaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPenyewaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Data sewa.png"))); // NOI18N
        btnPenyewaan.setText("Data Penyewaan");
        btnPenyewaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPenyewaan.setIconTextGap(10);
        btnPenyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPenyewaanMouseClicked(evt);
            }
        });

        bntPenyewaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntPenyewaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pengembalian.png"))); // NOI18N
        bntPenyewaan.setText("Data Pengembalian");
        bntPenyewaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntPenyewaan.setIconTextGap(10);
        bntPenyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntPenyewaanMouseClicked(evt);
            }
        });

        bntlogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout.png"))); // NOI18N
        bntlogout.setText("Logout");
        bntlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntlogout.setIconTextGap(10);
        bntlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntlogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMobil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPelanggan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSopir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKaryawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPenyewaan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntPenyewaan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(bntlogout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSopir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPenyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bntPenyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSopirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSopirMouseClicked
        navigateToPanel(MainFrame.PanelType.SOPIR, "Data Sopir");
    }//GEN-LAST:event_btnSopirMouseClicked

    private void btnKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaryawanMouseClicked
        navigateToPanel(MainFrame.PanelType.KARYAWAN, "Data Karyawan");
    }//GEN-LAST:event_btnKaryawanMouseClicked

    private void btnPenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenyewaanMouseClicked
        navigateToPanel(MainFrame.PanelType.PENYEWAAN, "Data Penyewaan");
    }//GEN-LAST:event_btnPenyewaanMouseClicked

    private void bntPenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntPenyewaanMouseClicked
        navigateToPanel(MainFrame.PanelType.PENGEMBALIAN, "Data Pengembalian");
    }//GEN-LAST:event_bntPenyewaanMouseClicked

    private void bntlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntlogoutMouseClicked
        // Clear user session and redirect to login
        utils.UserSession.getInstance().clearSession();
        if (mainFrame != null) {
            mainFrame.redirectToLogin();
        } else {
            System.err.println("MainFrame reference is null, cannot redirect to login!");
        }
    }//GEN-LAST:event_bntlogoutMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnDashboardMouseClicked
        navigateToPanel(MainFrame.PanelType.DASHBOARD, "Dashboard");
    }// GEN-LAST:event_btnDashboardMouseClicked

    private void btnPelangganMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnPelangganMouseClicked
        navigateToPanel(MainFrame.PanelType.PELANGGAN, "Data Pelanggan");
    }// GEN-LAST:event_btnPelangganMouseClicked

    private void btnMobilMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnMobilMouseClicked
        navigateToPanel(MainFrame.PanelType.MOBIL, "Data Mobil");
    }// GEN-LAST:event_btnMobilMouseClicked

    /**
     * Helper method to handle panel navigation and error logging
     *
     * @param panelType The type of panel to navigate to
     * @param panelName The display name of the panel (for logging)
     */
    private void navigateToPanel(MainFrame.PanelType panelType, String panelName) {
        System.out.println(panelName + " clicked");
        if (mainFrame != null) {
            mainFrame.showPanel(panelType);
        } else {
            System.err.println("MainFrame reference is null!");
        }
    }

    /**
     * Set visibility of the Karyawan button based on user role
     *
     * @param visible true to show the button, false to hide it
     */
    public void setKaryawanButtonVisible(boolean visible) {
        if (btnKaryawan != null) {
            btnKaryawan.setVisible(visible);
        }
    }

    /**
     * Set access control based on user role
     *
     * @param role the user's role ("admin" or "staff")
     */
    public void setupRoleBasedAccess(String role) {
        if ("admin".equalsIgnoreCase(role)) {
            // Admin can access all features including Karyawan management
            setKaryawanButtonVisible(true);
        } else {
            // Staff cannot access Karyawan management
            setKaryawanButtonVisible(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bntPenyewaan;
    private javax.swing.JLabel bntlogout;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnKaryawan;
    private javax.swing.JLabel btnMobil;
    private javax.swing.JLabel btnPelanggan;
    private javax.swing.JLabel btnPenyewaan;
    private javax.swing.JLabel btnSopir;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
